### ISSUE TITLE
Fails on Pyboard with SD card fitted

### ISSUE THREAD

**Issue by peterhinch** [AmirHmZz/mpbridge#2]
This works fine if no SD card is fitted, showing a `/flash` directory with contents. If a card is fitted, the progress gets to 50% then stops.

**Comment by AmirHmZz** [comment]
Unfortunately I don't have PyBoard and I cannot also buy one because of restrictions in my country. I've tested it with `esp32` with `SDCard` and it worked without any problem. So I will probably need your help in order to fix this bug. But let me add some loggers to debug parts more precisely.

**Comment by peterhinch** [comment]
(Just in case you're unaware). The Pyboard with an SD card looks like this
```python
>>> os.listdir('/')
['flash', 'sd']
```
The fact that your code stops at 50% exactly suggests it may be reading one of these. My guess is that it's reading the SD card. This is based on the length of time to get to 50% and the fact that my Flash directory is almost empty.

**Comment by AmirHmZz** [comment]
Can you install package from PyPI and try again?

**Comment by peterhinch** [comment]
This worked fine with a Pico and with an ESP32-S3. The Pyboard 1.1 did this:
```python
[adminpete@capybara]: ~
$ mpbridge start /dev/ttyACM0
Traceback (most recent call last):
  File "/usr/local/bin/mpbridge", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mpbridge/shell.py", line 17, in start
    bridge.start(port)
  File "/usr/local/lib/python3.8/dist-packages/mpbridge/bridge.py", line 16, in start
    pyb.copy_all(dest_dir_path=tmp_dir_path)
  File "/usr/local/lib/python3.8/dist-packages/mpbridge/pyboard.py", line 84, in copy_all
    fs_records = self.fs_recursive_listdir()
  File "/usr/local/lib/python3.8/dist-packages/mpbridge/pyboard.py", line 38, in fs_recursive_listdir
    self.exec_(RECURSIVE_LS, data_consumer=consumer)
  File "/usr/local/lib/python3.8/dist-packages/mpremote/pyboard.py", line 467, in exec_
    raise PyboardError("exception", ret, ret_err)
mpremote.pyboard.PyboardError: ('exception', b'', b'Traceback (most recent call last):\r\n  File "<stdin>", line 13, in <module>\r\n  File "<stdin>", line 11, in iter_dir\r\n  File "<stdin>", line 6, in iter_dir\r\nOSError: [Errno 19] ENODEV\r\n')
```

**Comment by AmirHmZz** [comment]
Can you copy `RECURSIVE_LS` code located in `mpbridge/pyboard.py` into `main.py` of MicroPython project and debug which line exactly is causing this?

**Comment by peterhinch** [comment]
My `main.py` on the Pyboard's SD card now contains
```python
RECURSIVE_LS = """
from os import ilistdir
from gc import collect
def iter_dir(dir_path):
    collect()
    for item in ilistdir(dir_path):
        idir = f"{dir_path}/{item[0]}"
        if item[1] == 0x8000:
            yield idir, True
        else:
            yield from iter_dir(idir)
            yield idir, False
for item in iter_dir(""):
    print(item, end=",")
"""
```
The outcome was
```python
[adminpete@capybara]: ~
$ mpbridge start /dev/ttyACM0
Traceback (most recent call last):
  File "/usr/local/bin/mpbridge", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mpbridge/shell.py", line 17, in start
    bridge.start(port)
  File "/usr/local/lib/python3.8/dist-packages/mpbridge/bridge.py", line 16, in start
    pyb.copy_all(dest_dir_path=tmp_dir_path)
  File "/usr/local/lib/python3.8/dist-packages/mpbridge/pyboard.py", line 84, in copy_all
    fs_records = self.fs_recursive_listdir()
  File "/usr/local/lib/python3.8/dist-packages/mpbridge/pyboard.py", line 38, in fs_recursive_listdir
    self.exec_(RECURSIVE_LS, data_consumer=consumer)
  File "/usr/local/lib/python3.8/dist-packages/mpremote/pyboard.py", line 467, in exec_
    raise PyboardError("exception", ret, ret_err)
mpremote.pyboard.PyboardError: ('exception', b'', b'Traceback (most recent call last):\r\n  File "<stdin>", line 13, in <module>\r\n  File "<stdin>", line 11, in iter_dir\r\n  File "<stdin>", line 6, in iter_dir\r\nOSError: [Errno 19] ENODEV\r\n')
```
I tried also populating a `main.py` on the flash drive with the same code, but it had no effect. The SD card normally takes priority.

**Comment by AmirHmZz** [comment]
Thanks but I meant to flash a `main.py` containing this :
```Python
from os import ilistdir
from gc import collect
def iter_dir(dir_path):
    collect()
    for item in ilistdir(dir_path):
        idir = f"{dir_path}/{item[0]}"
        if item[1] == 0x8000:
            yield idir, True
        else:
            yield from iter_dir(idir)
            yield idir, False
for item in iter_dir(""):
    print(item, end=",")
```
Directly in your pyboard in order to make pyboard run it without any interaction with `mpbridge`.

**Comment by peterhinch** [comment]
OK, the outcome on a soft boot is:
```python
MicroPython v1.19.1-617-g43dd3ea74 on 2022-11-08; PYBv1.1 with STM32F405RG
Type "help()" for more information.
>>> 
>>> 
MPY: sync filesystems
MPY: soft reboot
Traceback (most recent call last):
  File "main.py", line 12, in <module>
  File "main.py", line 10, in iter_dir
  File "main.py", line 5, in iter_dir
OSError: [Errno 19] ENODEV
MicroPython v1.19.1-617-g43dd3ea74 on 2022-11-08; PYBv1.1 with STM32F405RG
Type "help()" for more information.
>>> 
```

**Comment by peterhinch** [comment]
I don't know if this helps:
```python
>>> from os import listdir
>>> listdir("")
['sched', 'gui', 'boot.py', 'main.py', 'rats.py', 'lcopy.mpy', 'drivers', 'color_setup.py', 'font10.py', 'font6.py', 'font14.py', 'metrics.py', 'primitives', 'lcd_local.py', 'message_test.py', 'as_drivers', 'fsdump.py', 'sdcard.py', 'sdcard_mod.py', 'hardware_setup.py', 'rats91.mpy', 'data', 'auart.py', 'umsgpack', 'asyntest.py', 'play_tone.py', 'play.py', 'spies.wav', 'test_rec11.wav', 'record.py', 'sine.py', 'sin', 'play_sine.py', 'play_wav.py', 'side-to-side-8k-16bits-stereo.wav', 'music-16k-32bits-stereo.wav', 'music-16k-16bits-stereo.wav', 'monitor.py', 'rats102.py', 'fir_py.py', 'firtest.py', 'fir.py', 'avg.py', 'avgtest.py', 'avg_pico.py', 'rats1.py', 'rats10.py', 'vs1053_syn.py', 'eeprom_spi.py', 'eep_spi.py', 'bdevice.py', 'neopixel.py', 'rats7.py', 'rats36.py', 'aswitch.py', 'rats42.py', 'r.py', 'events.py', '__init__.py', 'threadsafe_event.py', 'threadsafe']
>>> listdir("/")
['flash', 'sd']
>>> listdir("/sd")
['sched', 'gui', 'boot.py', 'main.py', 'rats.py', 'lcopy.mpy', 'drivers', 'color_setup.py', 'font10.py', 'font6.py', 'font14.py', 'metrics.py', 'primitives', 'lcd_local.py', 'message_test.py', 'as_drivers', 'fsdump.py', 'sdcard.py', 'sdcard_mod.py', 'hardware_setup.py', 'rats91.mpy', 'data', 'auart.py', 'umsgpack', 'asyntest.py', 'play_tone.py', 'play.py', 'spies.wav', 'test_rec11.wav', 'record.py', 'sine.py', 'sin', 'play_sine.py', 'play_wav.py', 'side-to-side-8k-16bits-stereo.wav', 'music-16k-32bits-stereo.wav', 'music-16k-16bits-stereo.wav', 'monitor.py', 'rats102.py', 'fir_py.py', 'firtest.py', 'fir.py', 'avg.py', 'avgtest.py', 'avg_pico.py', 'rats1.py', 'rats10.py', 'vs1053_syn.py', 'eeprom_spi.py', 'eep_spi.py', 'bdevice.py', 'neopixel.py', 'rats7.py', 'rats36.py', 'aswitch.py', 'rats42.py', 'r.py', 'events.py', '__init__.py', 'threadsafe_event.py', 'threadsafe']
>>> listdir("/flash")
['boot.py', 'main.py', 'pybcdc.inf', 'README.txt', 'upower.py', 'ttest.py', 'sdcard.py', 'sdcard_mod.py']
>>> 
```

**Comment by AmirHmZz** [comment]
@peterhinch of course that helped! Would you please flash this one in `main.py` ?

```Python
def iter_dir(dir_path):
    collect()
    for item in ilistdir(dir_path):
        if dir_path[-1] != "/":
            dir_path += "/"
        idir = f"{dir_path}{item[0]}"
        if item[1] == 0x8000:
            yield idir, True
        else:
            yield from iter_dir(idir)
            yield idir, False


for item in iter_dir("/"):
    print(item, end=",")
```

**Comment by peterhinch** [comment]
```python
MicroPython v1.19.1-617-g43dd3ea74 on 2022-11-08; PYBv1.1 with STM32F405RG
Type "help()" for more information.
>>> 
>>> 
MPY: sync filesystems
MPY: soft reboot
('/flash/boot.py', True),('/flash/main.py', True),('/flash/pybcdc.inf', True),('/flash/README.txt', True),('/flash/upower.py', True),('/flash/ttest.py', True),('/flash/sdcard.py', True),('/flash/sdcard_mod.py', True),('/flash', False),('/sd/sched/crontest.py', True),('/sd/sched/primitives/__init__.py', True),('/sd/sched/primitives', False),('/sd/sched/cron.py', True),('/sd/sched/asynctest.py', True),('/sd/sched/synctest.py', True),('/sd/sched/sched.py', True),('/sd/sched/__init__.py', True),('/sd/sched', False),('/sd/gui/primitives/delay_ms.py', True),('/sd/gui/primitives/__init__.py', True),('/sd/gui/primitives', False),('/sd/gui/widgets/buttons.py', True),('/sd/gui/widgets/knob.py', True),('/sd/gui/widgets/dialog.py', True),('/sd/gui/widgets/__init__.py', True),('/sd/gui/widgets/textbox.py', True),('/sd/gui/widgets/dial.py', True),('/sd/gui/widgets/meter.py', True),('/sd/gui/widgets/listbox.py', True),('/sd/gui/widgets/vectors.py', True),('/sd/gui/widgets/checkbox.py', True),('/sd/gui/widgets/sliders.py', True),('/sd/gui/widgets/pad.py', True),('/sd/gui/widgets/label.py', True),('/sd/gui/widgets/led.py', True),('/sd/gui/widgets/dropdown.py', True),('/sd/gui/widgets/scale.py', True),('/sd/gui/widgets', False),('/sd/gui/demos/ldb_if.py', True),('/sd/gui/demos/__init__.py', True),('/sd/gui/demos/lpt.py', True),('/sd/gui/demos/lhst.py', True),('/sd/gui/demos/lscale.py', True),('/sd/gui/demos/lbt.py', True),('/sd/gui/demos/ldd.py', True),('/sd/gui/demos/vtest.py', True),('/sd/gui/demos/tbox.py', True),('/sd/gui/demos/ldb.py', True),('/sd/gui/demos/lvst.py', True),('/sd/gui/demos/lkt.py', True),('/sd/gui/demos/lptg.py', True),('/sd/gui/demos', False),('/sd/gui/framebuf_utils/framebuf_utils.c', True),('/sd/gui/framebuf_utils/Makefile', True),('/sd/gui/framebuf_utils/__init__.py', True),('/sd/gui/framebuf_utils/test.py', True),('/sd/gui/framebuf_utils/framebuf_utils.mpy', True),('/sd/gui/framebuf_utils', False),('/sd/gui/core/lcd160cr.py', True),('/sd/gui/core/__init__.py', True),('/sd/gui/core/lplot.py', True),('/sd/gui/core/lcd160_gui.py', True),('/sd/gui/core/constants.py', True),('/sd/gui/core', False),('/sd/gui', False),('/sd/boot.py', True),('/sd/main.py', True),('/sd/rats.py', True),('/sd/lcopy.mpy', True),('/sd/drivers/ssd1306/ssd1306.py', True),('/sd/drivers/ssd1306', False),('/sd/drivers/sharp/__init__.py', True),('/sd/drivers/sharp/clock_batt.py', True),('/sd/drivers/sharp/clocktest.py', True),('/sd/drivers/sharp/sharp.py', True),('/sd/drivers/sharp/sharptest.py', True),('/sd/drivers/sharp', False),('/sd/drivers/ili93xx/ili9341.py', True),('/sd/drivers/ili93xx', False),('/sd/drivers/ssd1351/test_colors_96.py', True),('/sd/drivers/ssd1351/test96_row.py', True),('/sd/drivers/ssd1351/__init__.py', True),('/sd/drivers/ssd1351/ssd1351.py', True),('/sd/drivers/ssd1351/test128_row.py', True),('/sd/drivers/ssd1351/ssd1351_4bit.py', True),('/sd/drivers/ssd1351/ssd1351_generic.py', True),('/sd/drivers/ssd1351/ssd1351_16bit.py', True),('/sd/drivers/ssd1351', False),('/sd/drivers/st7735r/st7735r_4bit.py', True),('/sd/drivers/st7735r/st7735r.py', True),('/sd/drivers/st7735r/st7735r144.py', True),('/sd/drivers/st7735r/st7735r144_4bit.py', True),('/sd/drivers/st7735r/st7735_notes', True),('/sd/drivers/st7735r', False),('/sd/drivers/ssd1331/test_colors.py', True),('/sd/drivers/ssd1331/ssd1331.py', True),('/sd/drivers/ssd1331/ssd1331_16bit.py', True),('/sd/drivers/ssd1331/__init__.py', True),('/sd/drivers/ssd1331', False),('/sd/drivers', False),('/sd/color_setup.py', True),('/sd/font10.py', True),('/sd/font6.py', True),('/sd/font14.py', True),('/sd/metrics.py', True),('/sd/primitives/barrier.py', True),('/sd/primitives/irq_event.py', True),('/sd/primitives/__init__.py', True),('/sd/primitives/semaphore.py', True),('/sd/primitives/pushbutton.py', True),('/sd/primitives/tests/__init__.py', True),('/sd/primitives/tests/adctest.py', True),('/sd/primitives/tests/asyntest.py', True),('/sd/primitives/tests/irq_event_test.py', True),('/sd/primitives/tests/delay_test.py', True),('/sd/primitives/tests/switches.py', True),('/sd/primitives/tests/message_test.py', True),('/sd/primitives/tests/encoder_test.py', True),('/sd/primitives/tests/private.py', True),('/sd/primitives/tests/encoder_stop.py', True),('/sd/primitives/tests/wait_test.py', True),('/sd/primitives/tests/event_test.py', True),('/sd/primitives/tests', False),('/sd/primitives/queue.py', True),('/sd/primitives/aadc.py', True),('/sd/primitives/condition.py', True),('/sd/primitives/switch.py', True),('/sd/primitives/message.py', True),('/sd/primitives/delay_ms.py', True),('/sd/primitives/delay_ms_new.py', True),('/sd/primitives/delay_ms_io.py', True),('/sd/primitives/delay_ms_next.py', True),('/sd/primitives/encoder.py', True),('/sd/primitives/encoder_async.py', True),('/sd/primitives/events.py', True),('/sd/primitives/ringbuf_queue.py', True),('/sd/primitives', False),('/sd/lcd_local.py', True),('/sd/message_test.py', True),('/sd/as_drivers/htu21d/__init__.py', True),('/sd/as_drivers/htu21d/htu_test.py', True),('/sd/as_drivers/htu21d/htu21d_mc.py', True),('/sd/as_drivers/htu21d', False),('/sd/as_drivers/client_server/userver.py', True),('/sd/as_drivers/client_server/heartbeat.py', True),('/sd/as_drivers/client_server/uclient.py', True),('/sd/as_drivers/client_server', False),('/sd/as_drivers/hd44780/alcdtest.py', True),('/sd/as_drivers/hd44780/__init__.py', True),('/sd/as_drivers/hd44780/notes', True),('/sd/as_drivers/hd44780/alcd.py', True),('/sd/as_drivers/hd44780', False),('/sd/as_drivers/nec_ir/__init__.py', True),('/sd/as_drivers/nec_ir/aremote.py', True),('/sd/as_drivers/nec_ir/art1.py', True),('/sd/as_drivers/nec_ir/art.py', True),('/sd/as_drivers/nec_ir', False),('/sd/as_drivers/syncom/main.py', True),('/sd/as_drivers/syncom/sr_passive.py', True),('/sd/as_drivers/syncom/syncom.py', True),('/sd/as_drivers/syncom/sr_init.py', True),('/sd/as_drivers/syncom', False),('/sd/as_drivers/metrics/__init__.py', True),('/sd/as_drivers/metrics/metrics.py', True),('/sd/as_drivers/metrics', False),('/sd/as_drivers/as_GPS/log.kml', True),('/sd/as_drivers/as_GPS/as_GPS_time.py', True),('/sd/as_drivers/as_GPS/log_kml.py', True),('/sd/as_drivers/as_GPS/astests.py', True),('/sd/as_drivers/as_GPS/as_tGPS.py', True),('/sd/as_drivers/as_GPS/as_rwGPS.py', True),('/sd/as_drivers/as_GPS/baud.py', True),('/sd/as_drivers/as_GPS/ast_pbrw.py', True),('/sd/as_drivers/as_GPS/ast_pb.py', True),('/sd/as_drivers/as_GPS/as_GPS.py', True),('/sd/as_drivers/as_GPS/__init__.py', True),('/sd/as_drivers/as_GPS/astests_pyb.py', True),('/sd/as_drivers/as_GPS/as_rwGPS_time.py', True),('/sd/as_drivers/as_GPS/as_GPS_utils.py', True),('/sd/as_drivers/as_GPS', False),('/sd/as_drivers/i2c/i2c_resp.py', True),('/sd/as_drivers/i2c/i2c_init.py', True),('/sd/as_drivers/i2c/__init__.py', True),('/sd/as_drivers/i2c/asi2c.py', True),('/sd/as_drivers/i2c/i2c_esp.py', True),('/sd/as_drivers/i2c/asi2c_i.py', True),('/sd/as_drivers/i2c', False),('/sd/as_drivers/sched/primitives/__init__.py', True),('/sd/as_drivers/sched/primitives', False),('/sd/as_drivers/sched/asynctest.py', True),('/sd/as_drivers/sched/crontest.py', True),('/sd/as_drivers/sched/cron.py', True),('/sd/as_drivers/sched/__init__.py', True),('/sd/as_drivers/sched/synctest.py', True),('/sd/as_drivers/sched/sched.py', True),('/sd/as_drivers/sched', False),('/sd/as_drivers', False),('/sd/fsdump.py', True),('/sd/sdcard.py', True),('/sd/sdcard_mod.py', True),('/sd/hardware_setup.py', True),('/sd/rats91.mpy', True),('/sd/data', True),('/sd/auart.py', True),('/sd/umsgpack/mp_load.py', True),('/sd/umsgpack/as_load.py', True),('/sd/umsgpack/umsgpack_ext.py', True),('/sd/umsgpack/mp_dump.py', True),('/sd/umsgpack/__init__.py', True),('/sd/umsgpack', False),('/sd/asyntest.py', True),('/sd/play_tone.py', True),('/sd/play.py', True),('/sd/spies.wav', True),('/sd/test_rec11.wav', True),('/sd/record.py', True),('/sd/sine.py', True),('/sd/sin', True),('/sd/play_sine.py', True),('/sd/play_wav.py', True),('/sd/side-to-side-8k-16bits-stereo.wav', True),('/sd/music-16k-32bits-stereo.wav', True),('/sd/music-16k-16bits-stereo.wav', True),('/sd/monitor.py', True),('/sd/rats102.py', True),('/sd/fir_py.py', True),('/sd/firtest.py', True),('/sd/fir.py', True),('/sd/avg.py', True),('/sd/avgtest.py', True),('/sd/avg_pico.py', True),('/sd/rats1.py', True),('/sd/rats10.py', True),('/sd/vs1053_syn.py', True),('/sd/eeprom_spi.py', True),('/sd/eep_spi.py', True),('/sd/bdevice.py', True),('/sd/neopixel.py', True),('/sd/rats7.py', True),('/sd/rats36.py', True),('/sd/aswitch.py', True),('/sd/rats42.py', True),('/sd/r.py', True),('/sd/events.py', True),('/sd/__init__.py', True),('/sd/threadsafe_event.py', True),('/sd/threadsafe/__init__.py', True),('/sd/threadsafe/threadsafe_queue.py', True),('/sd/threadsafe/threadsafe_event.py', True),('/sd/threadsafe', False),('/sd', False),MicroPython v1.19.1-617-g43dd3ea74 on 2022-11-08; PYBv1.1 with STM32F405RG
Type "help()" for more information.
>>> 
```

**Comment by peterhinch** [comment]
It is perhaps worth noting that there are other circumstances in which the `/` directory can have subdirectories. On any MP platform it's possible to mount devices onto the root. For example [this library](https://github.com/peterhinch/micropython_eeprom) lets you do this with devices such as Flash and EEPROM chips. See [this code](https://github.com/peterhinch/micropython_eeprom/blob/5037f0999a495a3d1881ecaadcbfca8875a326db/flash/flash_test.py#L108) for an example of such mounting.

**Comment by AmirHmZz** [comment]
@peterhinch Would you please upgrade `mpbridge` to version `0.1.1` and try again with pyboard? consider doing it with **sudo** command : `sudo pip install -U mpbridge`

**Comment by peterhinch** [comment]
That works fine. I edited a few files and deleted some: all occurred correctly. Later I will test a Pyboard D with external Flash chips mounted, but I feel confident this will work. It will be a very useful tool for managing such filesystems.

A couple of comments.
 1. It's not clear how to quit the application. `ctrl-c` leaves the USB in a state that requires a hardware reset to run mpremote or rshell.
 2. It would be good if there were a means to start an alternative file manager. Or, failing that, just print the location of the filesystem  in the `/tmp` directory.

**Comment by peterhinch** [comment]
I'm afraid it doesn't like my mounted filesystem. I created a `main.py` as follows:
```python
import time
from pyb import LED
led = LED(1)
time.sleep(5)
led.on()
time.sleep(1)
led.off()
import os
from flash_test import get_device  # set up the hardware
os.mount(get_device(), '/fl_ext')
```
On power up the LED flashes after 5 secs. If I then run `mpremote` I can list the contents of `/fl_ext` which is a single file. If I power cycle, wait for the LED flash, and run mpbridge, this is the outcome:
```
$ mpbridge start /dev/ttyACM0
[reads the contents of /flash, then reads the contents of /sd]
 ↓ Getting /sd/flashbdev2.py		 |████████████████████| 100% Complete
 ↓ Getting /sd/flashbdev3.py		 |████████████████████| 100% Complete
 ✓ Copied all files successfully

(exo-open:136056): dbind-WARNING **: 11:42:30.223: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

(xfce4-mime-helper:136063): dbind-WARNING **: 11:42:30.246: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```
After this the file manager shows the contents of `/sd` and `/flash` correctly, but there is no sign of `/fl_ext`.

**Comment by peterhinch** [comment]
A search suggested putting
```
export NO_AT_BRIDGE=1
```
in `/etc/environment`. This suppressed the error messages but `/fl_ext` was still not recognised.

I'm afraid this stuff is beyond me :(

**Comment by peterhinch** [comment]
This appears to be a MicroPython problem: devices mounted with `os.mount` seem to be dismounted under some circumstances. I'll investigate.

I'll close this as the problem originally reported is fixed.

**Comment by AmirHmZz** [comment]
@peterhinch Thanks for your cooperation. Would you please open an issue for this one :

> It would be good if there were a means to start an alternative file manager. Or, failing that, just print the location of the filesystem in the /tmp directory.

And another for this one https://github.com/AmirHmZz/mpbridge/issues/2#issuecomment-1364517664. I have some idea for the second one and I think It would be better to discuss about it in another issue.

Thanks again :)

**Comment by AmirHmZz** [comment]
@peterhinch Another point that I want you to know is:

> mpbridge start /dev/ttyACM0

There's no need to type the full path anymore. You can now use [port's short form](https://github.com/AmirHmZz/mpbridge#how-to-use). In your case it is just enough to run `mpbridge start a0`.

**Comment by peterhinch** [comment]
I have raised [this issue](https://github.com/micropython/micropython/issues/10328). Clearly `mpbridge` cannot be expected to work if the mountpoint is unstable.

**Comment by AmirHmZz** [comment]
I've had this in my mind to execute the mounting part before bridge starts. If it's already mounted, an error will be raised. I think It's better to open an issue about it and talk about possible solutions. At least If we found no way to fix this we will wait until MicroPython fixes it.
